export { default as Hero } from './Hero'
export { default as Productshowcase } from './Productshowcase'
export { default as Features } from './Features'
export { default as Benefits } from './Benefits'
export { default as Testimonials } from './Testimonials'
export { default as Newsletter } from './Newsletter'